// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/pablojhp.pergo/internal/session"
	"github.com/pablojhp.pergo/templates/components"
	"github.com/pablojhp.pergo/templates/layout"
)

// DeviceListPage renders the full device management page with layout.
// DeviceListPage renders the full device management page with layout.
func DeviceListPage(devices []*session.Device) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layout.Base("Conexões", DeviceListContent(devices)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// DeviceListContent renders the device list content (HTMX fragment or full page body).
func DeviceListContent(devices []*session.Device) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"page-header flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6\"><h1 class=\"text-2xl font-bold tracking-tight text-zinc-900\">Conexões</h1><button class=\"btn btn-black bg-black text-white hover:bg-zinc-800 border-none btn-sm\" hx-get=\"/admin/devices/pair-form\" hx-target=\"#pair-form-area\" hx-swap=\"innerHTML\">Link WhatsApp Web</button></div><div id=\"pair-form-area\" class=\"mb-6\"></div><div class=\"section bg-white border border-zinc-200 rounded-lg p-5 shadow-sm mb-6\"><h2 class=\"text-sm font-bold text-zinc-500 uppercase tracking-wider mb-4\">Dispositivos WhatsApp Web Ativos</h2><table class=\"table w-full text-zinc-700\" id=\"device-table\"><thead><tr class=\"bg-zinc-50 text-zinc-500 border-b border-zinc-200\"><th class=\"px-4 py-2 text-left text-xs font-semibold uppercase\">JID</th><th class=\"px-4 py-2 text-left text-xs font-semibold uppercase\">Phone</th><th class=\"px-4 py-2 text-left text-xs font-semibold uppercase\">Status</th><th class=\"px-4 py-2 text-left text-xs font-semibold uppercase\">Workspace</th><th class=\"px-4 py-2 text-left text-xs font-semibold uppercase\">Actions</th></tr></thead> <tbody id=\"device-list-body\" class=\"divide-y divide-zinc-200\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, d := range devices {
			templ_7745c5c3_Err = components.DeviceCard(d).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if len(devices) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<tr><td colspan=\"5\" class=\"px-4 py-6 text-center text-zinc-400 italic\">Nenhum dispositivo emparelhado. Clique em \"Link WhatsApp Web\" para começar.</td></tr>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</tbody></table></div><div class=\"section bg-white border border-zinc-200 rounded-lg p-5 shadow-sm\"><h2 class=\"text-sm font-bold text-zinc-500 uppercase tracking-wider mb-4\">Caixas de Entrada por Canal (Inboxes)</h2><div class=\"grid grid-cols-1 md:grid-cols-3 gap-4\"><div class=\"bg-zinc-50 border border-zinc-200 rounded-lg p-4 flex flex-col justify-between gap-4\"><div><h3 class=\"font-bold text-zinc-900 text-sm\">WhatsApp Web</h3><p class=\"text-xs text-zinc-400 mt-1\">Mensagens recebidas no WhatsApp Web emparelhado.</p></div><div><a href=\"/admin/inbox/whatsapp\" class=\"btn btn-xs btn-outline border-zinc-300 text-zinc-700 hover:bg-zinc-100 font-semibold w-full text-center\">Abrir Inbox</a></div></div><div class=\"bg-zinc-50 border border-zinc-200 rounded-lg p-4 flex flex-col justify-between gap-4\"><div><h3 class=\"font-bold text-zinc-900 text-sm\">WhatsApp Cloud</h3><p class=\"text-xs text-zinc-400 mt-1\">Mensagens recebidas via API Oficial (WABA).</p></div><div><a href=\"/admin/inbox/whatsapp_cloud\" class=\"btn btn-xs btn-outline border-zinc-300 text-zinc-700 hover:bg-zinc-100 font-semibold w-full text-center\">Abrir Inbox</a></div></div><div class=\"bg-zinc-50 border border-zinc-200 rounded-lg p-4 flex flex-col justify-between gap-4\"><div><h3 class=\"font-bold text-zinc-900 text-sm\">Telegram</h3><p class=\"text-xs text-zinc-400 mt-1\">Mensagens recebidas via bot do Telegram.</p></div><div><a href=\"/admin/inbox/telegram\" class=\"btn btn-xs btn-outline border-zinc-300 text-zinc-700 hover:bg-zinc-100 font-semibold w-full text-center\">Abrir Inbox</a></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// PairForm renders the QR pairing initiation form.
// Triggered by the "Link Device" button via HTMX.
func PairForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"pair-form card\"><h3>Link WhatsApp Device</h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.BanWarning().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<form hx-post=\"/admin/devices/pair\" hx-target=\"#qr-area\" hx-swap=\"innerHTML\"><div class=\"form-group\"><label for=\"phone\">Phone Number</label> <input id=\"phone\" name=\"phone\" type=\"tel\" class=\"form-control\" placeholder=\"+5511999999999\" required></div><button type=\"submit\" class=\"btn btn-primary\">Start Pairing</button></form><div id=\"qr-area\" class=\"qr-area\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// QRFragment renders the current QR code state as an HTMX-refreshable fragment.
// code: raw QR code string (empty if not yet available)
// phone: phone number being paired
// status: "pending", "paired", "error"
// message: human-readable status message
func QRFragment(code string, phone string, status string, message string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"qr-fragment\" id=\"qr-area\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.BanWarning().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<p class=\"qr-status\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(message)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/devices.templ`, Line: 124, Col: 32}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		switch status {
		case "pending":
			if code != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div class=\"qr-container\"><p class=\"qr-hint\">Scan this code with WhatsApp on your phone:</p><div class=\"qr-code-raw\" data-qr=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(code)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/devices.templ`, Line: 132, Col: 21}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" aria-label=\"QR Code\"><p class=\"qr-code-text\"><code>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(code)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/devices.templ`, Line: 135, Col: 43}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</code></p></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<div class=\"qr-loading\"><div class=\"spinner\"></div><p>Generating QR code...</p></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, " <div hx-get=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.ResolveAttributeValue("/admin/devices/qr?phone=" + phone)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/devices.templ`, Line: 145, Col: 48}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "\" hx-trigger=\"every 5s\" hx-target=\"#qr-area\" hx-swap=\"innerHTML\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case "paired":
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<div class=\"qr-success\"><p class=\"success-icon\">✅</p><p>Device paired successfully!</p><button class=\"btn btn-primary\" hx-get=\"/admin/devices\" hx-target=\"main\" hx-swap=\"innerHTML\">View Devices</button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case "error":
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "<div class=\"qr-error\"><p class=\"error-icon\">❌</p><p>Pairing failed. Please try again.</p><button class=\"btn btn-secondary\" hx-get=\"/admin/devices/pair-form\" hx-target=\"#pair-form-area\" hx-swap=\"innerHTML\">Try Again</button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
